### ISSUE TITLE
Add Galaxy J6 to working devices

### ISSUE THREAD

**Issue by tolukolvi** [Map-A-Droid/MAD-device-list#32]
Hi!
After quite some time experimenting I got Samsung Galaxy J6 (SM-J600FN)to work with MAD. It will not inject on stock Oreo/Pie roms, but requires Lineage GSI, which requires a bit of effort thou. Definitely not 'easy'. Also, the procedure needs to be exactly as follows:
Install TWRP 3.2.3 (unofficial)
Enter recovery, wipe system/data/cache/dalvik
Install Lineage GSI image and reboot to recovery
Install Vendor J6 and reboot to recovery
Install OpenGApps pico (other versions will not install, not enough space)
Install Magisk 20.1 (earlier versions didn't work)
Reboot to system
Install PogoDroid/RemoteGPSController
Systemize RGC using Link2SD and reboot
Smalipatch using only mock locations ticked (randomly stuck at 90%, just try different USB-ports)
Install and reboot to recovery
Wipe dalvik/cache (I got bootloop until I did this)
Configure 
Enjoy!

**Comment by krzee** [comment]
this is an "issue"
you meant to submit a PR. Do that and it'll likely be accepted
