### ISSUE TITLE
YA II

### ISSUE THREAD

**Issue by Laemmamen** [Map-A-Droid/MAD-device-list#34]
Hey guys

is there a workaround for flashing this devices
I am not able to change the firmware on the device 

Yagala YA-II | S905W | MAD rom | 18.1 | Yes | SD card (USB A to USB A untested) | ~20 min. | Only tried on one device! ROM and procedure exactly the same as X96 Mini
-- | -- | -- | -- | -- | -- | -- | --

i try to install it how explaint but nothing was working how expected
what do i wrong 
i copy the image with Burn card Maker
to the SD card
i put the sd card in the yagala device and then i try to enter the Rom mode with the AV button but then the device opens only the files app

and there i cannot choose any installation file
please help me to install the firmware

**Comment by Laemmamen** [comment]
hey i now have installed the Mad Software on the device 
But since that the remote is working no more i connected an keyboard and a mouse this helped 
but whe i starting Pokemon Go app the device won´t let me enter the Date of birth 

thanks for your help 
i won´t come throw this Process
is here someone usning this device and can help me

i can start apps and go into them but i cannot enter something while i locked in to Pokemon Go app

**Comment by TechG3n** [comment]
You should read the wiki:
https://github.com/Map-A-Droid/MAD-ATV/blob/master/README_installation.md:

.. * Now go to pokemon go and sign in. You will need to use scrcpy or teamviewer to enter data in to the pokemon go app.  ...

**Comment by ColdShadow80** [comment]
Also, MAD can fill birthday for you once you start PD and RGC and connect to your server
